"""Add auth clients products invoices

Revision ID: 767274cb0721
Revises: 001
Create Date: 2025-11-29 19:51:16.054617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767274cb0721'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###